export const GameConfig = {
  get WIDTH() {
    return window.innerWidth;
  },
  get HEIGHT() {
    return window.innerHeight;
  },
};

export const Levels = [
  {
    id: 1,
    order: 1,
    difficulty: 1,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 3,
    timeSeconds: 15,
  },
  {
    id: 2,
    order: 2,
    difficulty: 1,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 3,
    timeSeconds: 15,
  },
  {
    id: 3,
    order: 3,
    difficulty: 1,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 3,
    timeSeconds: 10,
  },
  {
    id: 4,
    order: 4,
    difficulty: 1,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 4,
    timeSeconds: 10,
  },
  {
    id: 5,
    order: 5,
    difficulty: 1,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 4,
    timeSeconds: 10,
  },
  {
    id: 6,
    order: 6,
    difficulty: 2,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 10,
  },
  {
    id: 7,
    order: 7,
    difficulty: 2,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 10,
  },
  {
    id: 8,
    order: 8,
    difficulty: 2,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 10,
  },
  {
    id: 9,
    order: 9,
    difficulty: 2,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 10,
  },
  {
    id: 10,
    order: 10,
    difficulty: 2,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 10,
  },
  {
    id: 11,
    order: 11,
    difficulty: 3,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 5,
  },
  {
    id: 12,
    order: 12,
    difficulty: 3,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 5,
  },
  {
    id: 13,
    order: 13,
    difficulty: 3,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 5,
    timeSeconds: 5,
  },
  {
    id: 14,
    order: 14,
    difficulty: 3,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 6,
    timeSeconds: 5,
  },
  {
    id: 15,
    order: 15,
    difficulty: 3,
    shapeSequence: ["sphere", "triangle"],
    colorCount: 7,
    timeSeconds: 5,
  }
];